version: '3.8'
services:
  api:
    build:
      context: ../
      dockerfile: wallet_dkoded/infra/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
